title = "Dan Feeny"
baseURL = "https://example.com"
# baseURL = "https://https://dnaod.github.com/website-portfolio/"
canonifyURLs = true
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Vancouver, BC"
email = "feeny.dan@gmail.com"
# favicon = "img/celtic tree of life.jpg"
firstName = "Dan"
lastName = "Feeny"
phone = "+1-778-995-1692"
profileImage = "img/Dan Feeny - Vancouver background mugshot.jpg"
showQr = false
showContact = true
showBoards  = true
# showCertifications = true
showSocializations = true
sections = ["skills","experience","contributions","creations", "publications","education"]


[params.google]

[params.google.analytics]
trackerID = "G-9XP67LYKYK"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/dan-feeny/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/dnaod/"

[[params.handles]]
    name = "Bluesky"
    link = "https://bsky.app/profile/danfeeny.bsky.social"
    icon = "bluesky"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"