title = "Dan Feeny"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Vancouver, BC"
email = "feeny.dan@gmail.com"
# favicon = "/favicon.ico"
firstName = "Dan"
lastName = "Feeny"
phone = "+1-778-995-1692"
profileImage = "img/celtic tree of life.jpg"
# showQr = true
showContact = true
showBoards  = true
# showCertifications = true
showSocializations = true
sections = ["skills","creations","experience","education","blog"]


[params.google]

[params.google.analytics]
# trackerID = "XX-123446-01"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/dan-feeny/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/dnaod/"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"